In [1]:
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={'a':10,'b':20,'c':30}

NameError: name 'np' is not defined

In [2]:
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={'a':10,'b':20,'c':30}

NameError: name 'np' is not defined

In [3]:
import numpy as np
import pandas as pd
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={'a':10,'b':20,'c':30}

In [4]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [6]:
pd.Series(data=arr)

0    10
1    20
2    30
dtype: int32

In [7]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [8]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [9]:
from numpy.random import randn
np.random.seed(101)

In [10]:
df=pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='P Q R S'.split())
df

P         Q         R         S
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [11]:
df['Q']

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: Q, dtype: float64

In [12]:
df[['P','Q','R']]

P         Q         R
A  2.706850  0.628133  0.907969
B  0.651118 -0.319318 -0.848077
C -2.018168  0.740122  0.528813
D  0.188695 -0.758872 -0.933237
E  0.190794  1.978757  2.605967

In [13]:
df.P

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: P, dtype: float64

In [14]:
type(df['P'])

pandas.core.series.Series

In [15]:
df['T']=df['P']+df['Q']


In [16]:
df

P         Q         R         S         T
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [17]:
df.drop('P',axis=1)

Q         R         S         T
A  0.628133  0.907969  0.503826  3.334983
B -0.319318 -0.848077  0.605965  0.331800
C  0.740122  0.528813 -0.589001 -1.278046
D -0.758872 -0.933237  0.955057 -0.570177
E  1.978757  2.605967  0.683509  2.169552

In [18]:
df.drop('new',axis=1,inplace=True)


KeyError: "['new'] not found in axis"

In [19]:
df.drop('Q',axis=1,inplace=True)


In [20]:
df

P         R         S         T
A  2.706850  0.907969  0.503826  3.334983
B  0.651118 -0.848077  0.605965  0.331800
C -2.018168  0.528813 -0.589001 -1.278046
D  0.188695 -0.933237  0.955057 -0.570177
E  0.190794  2.605967  0.683509  2.169552

In [21]:
df.drop('E',axis=0)

P         R         S         T
A  2.706850  0.907969  0.503826  3.334983
B  0.651118 -0.848077  0.605965  0.331800
C -2.018168  0.528813 -0.589001 -1.278046
D  0.188695 -0.933237  0.955057 -0.570177

In [22]:
df.loc['A']

P    2.706850
R    0.907969
S    0.503826
T    3.334983
Name: A, dtype: float64

In [23]:
df.iloc[2]

P   -2.018168
R    0.528813
S   -0.589001
T   -1.278046
Name: C, dtype: float64

In [24]:
df.loc['B','R']

-0.8480769834036315

In [25]:
df.loc[['A','B'],['P','S']]

P         S
A  2.706850  0.503826
B  0.651118  0.605965

In [26]:
df>0

P      R      S      T
A   True   True   True   True
B   True  False   True   True
C  False   True  False  False
D   True  False   True  False
E   True   True   True   True

In [27]:
df[df>0]

P         R         S         T
A  2.706850  0.907969  0.503826  3.334983
B  0.651118       NaN  0.605965  0.331800
C       NaN  0.528813       NaN       NaN
D  0.188695       NaN  0.955057       NaN
E  0.190794  2.605967  0.683509  2.169552

In [28]:
df[df['R']>0]

P         R         S         T
A  2.706850  0.907969  0.503826  3.334983
C -2.018168  0.528813 -0.589001 -1.278046
E  0.190794  2.605967  0.683509  2.169552

In [29]:
df[df['P']>0][['R','S']]

R         S
A  0.907969  0.503826
B -0.848077  0.605965
D -0.933237  0.955057
E  2.605967  0.683509

In [30]:
df

P         R         S         T
A  2.706850  0.907969  0.503826  3.334983
B  0.651118 -0.848077  0.605965  0.331800
C -2.018168  0.528813 -0.589001 -1.278046
D  0.188695 -0.933237  0.955057 -0.570177
E  0.190794  2.605967  0.683509  2.169552

In [32]:
df.reset_index()

index         P         R         S         T
0     A  2.706850  0.907969  0.503826  3.334983
1     B  0.651118 -0.848077  0.605965  0.331800
2     C -2.018168  0.528813 -0.589001 -1.278046
3     D  0.188695 -0.933237  0.955057 -0.570177
4     E  0.190794  2.605967  0.683509  2.169552

In [4]:
import pandas as pd
a=pd.Series([10,20,30])
print(a)

0    10
1    20
2    30
dtype: int64


In [13]:
from pandas import*
import numpy as np
a=Series([10,20,np.nan])
print(a)

0    10.0
1    20.0
2     NaN
dtype: float64


In [16]:
a=[10,11,12,'sachin']
print(a)
type(a)
b=pd.Series(a)
print(b)
type(b)

[10, 11, 12, 'sachin']
0        10
1        11
2        12
3    sachin
dtype: object


pandas.core.series.Series

In [49]:
a=[['sachin',90],['baju',91],['lalita',92]]
df=DataFrame(a,columns=['Name','makrs'])
a=df['Name']
print(a)
type(a)
df.head(n=5)
df.tail(2)

0    sachin
1      baju
2    lalita
Name: Name, dtype: object


Name  makrs
1    baju     91
2  lalita     92

In [27]:
a={'Name':['sachin','baju'],'Age':[20,26]}
print(a)
df=DataFrame(a)
print(df)

{'Name': ['sachin', 'baju'], 'Age': [20, 26]}
     Name  Age
0  sachin   20
1    baju   26


In [33]:
import pandas as pd
dates_d=pd.date_range('20201212',periods=10,freq='D')
print(dates_d)

DatetimeIndex(['2020-12-12', '2020-12-13', '2020-12-14', '2020-12-15',
               '2020-12-16', '2020-12-17', '2020-12-18', '2020-12-19',
               '2020-12-20', '2020-12-21'],
              dtype='datetime64[ns]', freq='D')


In [34]:
import pandas as pd
dates_m=pd.date_range('20201212',periods=10,freq='M')
print(dates_m)

DatetimeIndex(['2020-12-31', '2021-01-31', '2021-02-28', '2021-03-31',
               '2021-04-30', '2021-05-31', '2021-06-30', '2021-07-31',
               '2021-08-31', '2021-09-30'],
              dtype='datetime64[ns]', freq='M')


In [41]:
import pandas as pd
dates_y=pd.date_range('20201212',periods=10,freq='y')
print(dates_y)


DatetimeIndex(['2020-12-31', '2021-12-31', '2022-12-31', '2023-12-31',
               '2024-12-31', '2025-12-31', '2026-12-31', '2027-12-31',
               '2028-12-31', '2029-12-31'],
              dtype='datetime64[ns]', freq='A-DEC')


In [58]:
random=np.random.randn(10,4)#(row,column)
print(random)
df=DataFrame(random,columns=['A','B','C','D'])
df.head(n=5)
df.shape
print(df.columns)
df.info()

[[ 1.61153393e-01 -1.62451806e+00  5.75028340e-01 -1.90540733e-01]
 [ 8.29296634e-02  4.97234989e-01 -7.96775032e-01  1.58964253e-01]
 [ 5.67720511e-01 -2.41762727e-03  1.16347999e-01 -5.78004278e-01]
 [-1.45650854e+00 -2.92216216e-01  5.72720763e-01 -2.33632264e-01]
 [-1.26570562e+00 -3.53920881e+00 -7.41189826e-01 -1.10844653e+00]
 [ 7.52004466e-01 -1.61684643e+00 -6.85183685e-01  1.36859739e+00]
 [ 9.63702396e-01  1.34402510e+00  6.58803544e-01  4.45472737e-03]
 [ 7.66754434e-01  5.90620563e-01 -3.01104173e-01  2.01502722e+00]
 [ 7.15499534e-02 -2.96237079e-01 -1.50502296e+00  1.35928862e+00]
 [ 3.10793730e-01 -8.24572287e-02 -2.53349088e-01 -6.24011378e-01]]
Index(['A', 'B', 'C', 'D'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
A    10 non-null float64
B    10 non-null float64
C    10 non-null float64
D    10 non-null float64
dtypes: float64(4)
memory usage: 448.0 bytes


In [45]:
# create a data frame using pandas
import pandas as pd
dates_m=pd.date_range('20201212',periods=10,freq='M')
print(dates_m)
df=pd.DataFrame(random,index=dates_m,columns=list('ABCD'))
print(df)
df.info()
df.shape
pr


DatetimeIndex(['2020-12-31', '2021-01-31', '2021-02-28', '2021-03-31',
               '2021-04-30', '2021-05-31', '2021-06-30', '2021-07-31',
               '2021-08-31', '2021-09-30'],
              dtype='datetime64[ns]', freq='M')


ValueError: Shape of passed values is (1, 4), indices imply (10, 4)

In [3]:
random=np.random.randn(10,4)#(row,column)
df=DataFrame(random,columns=['A','B','C','D'])
df.head()
#remove missing value
df.dropna(axis=1)
df['A'].value.counts()
df.columns

NameError: name 'np' is not defined

In [78]:
random=np.random.randn(10,4)#(row,column)
df=DataFrame(random,columns=['A','B','C','D'])
print(df)
df.describe(include='all')

          A         B         C         D
0 -0.175047 -1.317209  0.326083 -0.395357
1 -0.099174 -1.121676 -0.730766  1.199869
2 -1.955427  2.604749  0.674520 -0.687837
3 -0.141054  0.062979  0.334188 -0.608681
4  1.038231 -0.267207  0.246824 -0.411051
5 -1.599230 -0.040067 -0.018369 -1.105406
6 -0.311923  1.580519  0.545240 -1.483827
7  0.674592  0.825735 -1.256232 -0.944166
8  0.485048 -0.519036  0.255738 -0.589441
9 -0.572885  1.947448  0.366208 -0.971928


A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean   -0.265687   0.375624   0.074343  -0.599782
std     0.938644   1.320176   0.604420   0.716347
min    -1.955427  -1.317209  -1.256232  -1.483827
25%    -0.507644  -0.456079   0.047929  -0.964988
50%    -0.158050   0.011456   0.290910  -0.648259
75%     0.338992   1.391823   0.358203  -0.455648
max     1.038231   2.604749   0.674520   1.199869

In [85]:
#slicing data
print(df[['A','B','C']])
df.head(4)
df[0:3]

          A         B         C
0 -0.175047 -1.317209  0.326083
1 -0.099174 -1.121676 -0.730766
2 -1.955427  2.604749  0.674520
3 -0.141054  0.062979  0.334188
4  1.038231 -0.267207  0.246824
5 -1.599230 -0.040067 -0.018369
6 -0.311923  1.580519  0.545240
7  0.674592  0.825735 -1.256232
8  0.485048 -0.519036  0.255738
9 -0.572885  1.947448  0.366208


A         B         C         D
0 -0.175047 -1.317209  0.326083 -0.395357
1 -0.099174 -1.121676 -0.730766  1.199869
2 -1.955427  2.604749  0.674520 -0.687837

In [2]:
df.iloc[1,1]

NameError: name 'df' is not defined

In [11]:
import numpy as np
from pandas import*
random=np.random.randn(10,4)#(row,column)
df=DataFrame(random,columns=['A','B','C','D'])
print(df)

df.columns
df.head()
df[0:3]

          A         B         C         D
0 -0.063981 -1.031341  1.715382 -0.129711
1 -1.298508  0.820848  0.135736 -0.567680
2  2.536826  0.029709 -0.917102  0.813153
3  0.512855  1.304639  2.177035  0.511345
4 -0.985024  0.191539 -1.679727  2.531644
5  0.864659 -2.803169  0.317410 -0.604270
6  0.185218  0.547368 -1.509322 -0.391762
7 -1.075888 -0.804480  0.956350  0.061078
8 -0.093573  0.412294  0.967333  0.890112
9  0.390259  0.752842 -2.112561  0.313643


A         B         C         D
0 -0.063981 -1.031341  1.715382 -0.129711
1 -1.298508  0.820848  0.135736 -0.567680
2  2.536826  0.029709 -0.917102  0.813153

In [15]:
df.loc[1,['A','B']]

A         B         C         D
0 -0.063981 -1.031341  1.715382 -0.129711
1 -1.298508  0.820848  0.135736 -0.567680
2  2.536826  0.029709 -0.917102  0.813153
3  0.512855  1.304639  2.177035  0.511345
4 -0.985024  0.191539 -1.679727  2.531644

In [16]:
df.iloc[1,['A','B']]

IndexError: .iloc requires numeric indexers, got ['A' 'B']

In [1]:
import numpy as np
from pandas import*
random=np.random.randn(10,4)#(row,column)
df=DataFrame(random,columns=['A','B','C','D'])
print(df)

          A         B         C         D
0  1.414365  0.600650  0.076221 -0.767149
1 -0.023717 -0.180325 -0.047076  0.871254
2 -0.555679  0.921508  0.758076  1.265598
3 -1.283451  1.593262 -1.391287 -1.138962
4 -0.193171 -1.244311  0.175949 -1.281336
5  0.298673 -2.391865 -0.448865  1.750248
6  0.787805 -0.110529  0.781441 -0.327610
7 -0.421259  0.251655 -0.030658  1.206020
8 -0.314996 -0.161973 -1.237681 -1.842497
9  0.541924  0.191258 -0.176892 -0.335691


In [2]:
df.iloc[:6,:2]

A         B
0  1.414365  0.600650
1 -0.023717 -0.180325
2 -0.555679  0.921508
3 -1.283451  1.593262
4 -0.193171 -1.244311
5  0.298673 -2.391865

In [3]:
df.iloc[[0,1,5,6,8]]

A         B         C         D
0  1.414365  0.600650  0.076221 -0.767149
1 -0.023717 -0.180325 -0.047076  0.871254
5  0.298673 -2.391865 -0.448865  1.750248
6  0.787805 -0.110529  0.781441 -0.327610
8 -0.314996 -0.161973 -1.237681 -1.842497

In [5]:
df.iloc[:,[-1:-3]]

SyntaxError: invalid syntax (<ipython-input-5-47d1a0a62bd1>, line 1)

In [7]:
#indexing or slicing the data frames
#begin:end:step
#default step value +1
#default begin value 0
#default end : length

df.iloc[:,-1:-3:-1]


        

D         C
0 -0.767149  0.076221
1  0.871254 -0.047076
2  1.265598  0.758076
3 -1.138962 -1.391287
4 -1.281336  0.175949
5  1.750248 -0.448865
6 -0.327610  0.781441
7  1.206020 -0.030658
8 -1.842497 -1.237681
9 -0.335691 -0.176892

In [8]:
df.iloc[:8:2,:-4:-2]

D         B
0 -0.767149  0.600650
2  1.265598  0.921508
4 -1.281336 -1.244311
6 -0.327610 -0.110529

In [12]:
df.iloc[::-3,-2::-2]

C         A
9 -0.176892  0.541924
6  0.781441  0.787805
3 -1.391287 -1.283451
0  0.076221  1.414365

In [20]:
#concatinating the data(combining the data frames) &Descriptive Statistics
df.drop(columns=['A','B'])



KeyError: "['A' 'B'] not found in axis"

In [21]:
df.drop(columns=['A','B'])

KeyError: "['A' 'B'] not found in axis"

In [22]:
import numpy as np
from pandas import*
random=np.random.randn(10,4)#(row,column)
df=DataFrame(random,columns=['A','B','C','D'])
print(df)

          A         B         C         D
0  0.485978  0.829025  0.001171  0.298610
1  0.867407  1.241333 -1.306161  0.431507
2  1.058104 -0.095195  0.570573  0.421449
3  0.137389 -0.380722 -0.180969  1.115322
4 -1.551867  1.652609 -0.172690 -0.332314
5 -0.793666 -1.117432 -1.984314 -1.521150
6 -0.820759 -0.337633 -0.428789 -0.384382
7  0.520808 -0.692852 -1.507939  1.151822
8  0.450333  0.089976  1.141500  1.080433
9  0.081068 -1.091425  0.190456  0.573994


In [23]:
df.drop(columns=['A','B'])

C         D
0  0.001171  0.298610
1 -1.306161  0.431507
2  0.570573  0.421449
3 -0.180969  1.115322
4 -0.172690 -0.332314
5 -1.984314 -1.521150
6 -0.428789 -0.384382
7 -1.507939  1.151822
8  1.141500  1.080433
9  0.190456  0.573994

In [24]:
df.drop(columns=['A','B'])
print(df)

          A         B         C         D
0  0.485978  0.829025  0.001171  0.298610
1  0.867407  1.241333 -1.306161  0.431507
2  1.058104 -0.095195  0.570573  0.421449
3  0.137389 -0.380722 -0.180969  1.115322
4 -1.551867  1.652609 -0.172690 -0.332314
5 -0.793666 -1.117432 -1.984314 -1.521150
6 -0.820759 -0.337633 -0.428789 -0.384382
7  0.520808 -0.692852 -1.507939  1.151822
8  0.450333  0.089976  1.141500  1.080433
9  0.081068 -1.091425  0.190456  0.573994


In [30]:
# here wee are going to concatenate two data frames in pandas 
#with help of concatenate func
import numpy as np
import pandas as pd
a=pd.DataFrame({'Name':['Sachin','Raki','chotu'],'Age':[20,21,35]})
b=pd.DataFrame({'Name':['Sachin','Riyaz'],'Age':[20,22]},index=[3,4])
print(a)
print(b)



     Name  Age
0  Sachin   20
1    Raki   21
2   chotu   35
     Name  Age
3  Sachin   20
4   Riyaz   22


In [31]:
r=pd.concat([a,b])
print(r)

     Name  Age
0  Sachin   20
1    Raki   21
2   chotu   35
3  Sachin   20
4   Riyaz   22


In [32]:
#print only the name
r['Name']

0    Sachin
1      Raki
2     chotu
3    Sachin
4     Riyaz
Name: Name, dtype: object

In [33]:
#check sachin is available or not
# to do this we have to compare with the sachin
r['Name']=='sachin' # case sensitive

0    False
1    False
2    False
3    False
4    False
Name: Name, dtype: bool

In [34]:
r['Name']=='Sachin'

0     True
1    False
2    False
3     True
4    False
Name: Name, dtype: bool

In [36]:
# if we want to return data instread of true or false
r[r['Name']=='Sachin']

Name  Age
0  Sachin   20
3  Sachin   20

In [37]:
# if you want to delete the duplicate value 
# drop_duplicates() ----use this function
r.drop_duplicates('Name')
# privious having 2 sachin name 

Name  Age
0  Sachin   20
1    Raki   21
2   chotu   35
4   Riyaz   22

In [44]:
# how to sort the value
r.sort_values('Name')
# sorting based on the capital latter ...after this this will check alphabates


Name  Age
1    Raki   21
4   Riyaz   22
0  Sachin   20
3  Sachin   20
2   chotu   35

In [47]:
r.sort_values('Age')

Name  Age
0  Sachin   20
3  Sachin   20
1    Raki   21
4   Riyaz   22
2   chotu   35

In [48]:
# use rename() function
r.rename(columns={'Name':'Emp_Name','Age':'Emp_Age'})

Emp_Name  Emp_Age
0   Sachin       20
1     Raki       21
2    chotu       35
3   Sachin       20
4    Riyaz       22

In [49]:
r.describe()

Age
count   5.000000
mean   23.600000
std     6.426508
min    20.000000
25%    20.000000
50%    21.000000
75%    22.000000
max    35.000000

In [50]:
r.describe(include='object')

Name
count        5
unique       4
top     Sachin
freq         2

In [52]:
r.describe(include='all')

Name        Age
count        5   5.000000
unique       4        NaN
top     Sachin        NaN
freq         2        NaN
mean       NaN  23.600000
std        NaN   6.426508
min        NaN  20.000000
25%        NaN  20.000000
50%        NaN  21.000000
75%        NaN  22.000000
max        NaN  35.000000

In [53]:
r.sum()

Name    SachinRakichotuSachinRiyaz
Age                            118
dtype: object

In [54]:
r['Age'].sum()

118

In [55]:
r['Age'].count()

5

In [56]:
r['Age'].mean()

23.6

In [57]:
r['Age'].median()

21.0

In [59]:
r['Age'].std()

6.4265076052238514

In [60]:
r['Age'].max()

35

In [61]:
r['Age'].min()

20

In [64]:
# merging or joining 
# merge() # arguments having (left,right,how,on,left_on,right_on)
student_details=pd.DataFrame({'S_name':['Sachin','Raki','Piyush','Ram','Chotu','Riyaz'],'Addrss':['Churu','Nagaur','Bharatpur','Samli','Rxl','Kasmir'],'Contact_num':[9928871084,9928757168,8072123442,7060068538,9521864647,7780807508]})
print(student_details)


   S_name     Addrss  Contact_num
0  Sachin      Churu   9928871084
1    Raki     Nagaur   9928757168
2  Piyush  Bharatpur   8072123442
3     Ram      Samli   7060068538
4   Chotu        Rxl   9521864647
5   Riyaz     Kasmir   7780807508


In [67]:
course_details=pd.DataFrame([['Sachin','Raki','Piyush','Ram','Chotu','Riyaz'],['data analytics','Python developer','Web_development','Mechine Lerning','Java developer','Data science'],[20000,13000,5000,23000,12000,17000]],columns=['S_name','Course_name','fee'])
print(course_details)

ValueError: 3 columns passed, passed data had 6 columns

In [69]:
course_details=pd.DataFrame({'S_name':['Sachin','Raki','Piyush','Ram','Chotu','Riyaz'],'Course_name':['data analytics','Python developer','Web_development','Mechine Lerning','Java developer','Data science'],'Fee':[20000,13000,5000,23000,12000,17000]})
print(course_details)

   S_name       Course_name    Fee
0  Sachin    data analytics  20000
1    Raki  Python developer  13000
2  Piyush   Web_development   5000
3     Ram   Mechine Lerning  23000
4   Chotu    Java developer  12000
5   Riyaz      Data science  17000


In [71]:
pd.merge(student_details,course_details,on='S_name')

S_name     Addrss  Contact_num       Course_name    Fee
0  Sachin      Churu   9928871084    data analytics  20000
1    Raki     Nagaur   9928757168  Python developer  13000
2  Piyush  Bharatpur   8072123442   Web_development   5000
3     Ram      Samli   7060068538   Mechine Lerning  23000
4   Chotu        Rxl   9521864647    Java developer  12000
5   Riyaz     Kasmir   7780807508      Data science  17000

In [72]:
pd.merge(student_details,course_details,on='S_name',how='inner')

S_name     Addrss  Contact_num       Course_name    Fee
0  Sachin      Churu   9928871084    data analytics  20000
1    Raki     Nagaur   9928757168  Python developer  13000
2  Piyush  Bharatpur   8072123442   Web_development   5000
3     Ram      Samli   7060068538   Mechine Lerning  23000
4   Chotu        Rxl   9521864647    Java developer  12000
5   Riyaz     Kasmir   7780807508      Data science  17000

In [75]:
#how to change the vlaue name
# place the chotu name in to ashish
# update the column name and also data
student_details['S_name'][0] # for 1 st value
student_details['S_name'][2]='ashish'

C:\Users\sachi\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


In [77]:
print(student_details)

   S_name     Addrss  Contact_num
0  Sachin      Churu   9928871084
1    Raki     Nagaur   9928757168
2  ashish  Bharatpur   8072123442
3     Ram      Samli   7060068538
4   Chotu        Rxl   9521864647
5   Riyaz     Kasmir   7780807508


In [78]:
student_details.iloc[1,0]='lalchand'

In [79]:
print(student_details)

     S_name     Addrss  Contact_num
0    Sachin      Churu   9928871084
1  lalchand     Nagaur   9928757168
2    ashish  Bharatpur   8072123442
3       Ram      Samli   7060068538
4     Chotu        Rxl   9521864647
5     Riyaz     Kasmir   7780807508


In [82]:
student_details=student_details.rename(columns={'S_name':'student_name'})

In [83]:
print(student_details)

  student_name     Addrss  Contact_num
0       Sachin      Churu   9928871084
1     lalchand     Nagaur   9928757168
2       ashish  Bharatpur   8072123442
3          Ram      Samli   7060068538
4        Chotu        Rxl   9521864647
5        Riyaz     Kasmir   7780807508


In [84]:
pd.merge(student_details,course_details,left_on='student_name',right_on='S_name',how='inner')


student_name  Addrss  Contact_num  S_name      Course_name    Fee
0       Sachin   Churu   9928871084  Sachin   data analytics  20000
1          Ram   Samli   7060068538     Ram  Mechine Lerning  23000
2        Chotu     Rxl   9521864647   Chotu   Java developer  12000
3        Riyaz  Kasmir   7780807508   Riyaz     Data science  17000

In [87]:
# outer join
# return only the matching and un matching data
# type-----full outre join,left outer join,right outer join
pd.merge(student_details,course_details,left_on='student_name',right_on='S_name',how='left',sort=True)


student_name     Addrss  Contact_num  S_name      Course_name      Fee
0        Chotu        Rxl   9521864647   Chotu   Java developer  12000.0
1          Ram      Samli   7060068538     Ram  Mechine Lerning  23000.0
2        Riyaz     Kasmir   7780807508   Riyaz     Data science  17000.0
3       Sachin      Churu   9928871084  Sachin   data analytics  20000.0
4       ashish  Bharatpur   8072123442     NaN              NaN      NaN
5     lalchand     Nagaur   9928757168     NaN              NaN      NaN